# syntax=docker/dockerfile:1.7

# ConBon production image.
#
# Multi-stage build:
#   deps      — install all deps (incl. dev — needed for `next build`,
#               `prisma generate`, and the TS prisma.config.ts loader)
#   builder   — generate the Prisma client + emit .next/standalone
#   migrator  — small one-shot image that runs `prisma migrate deploy`
#               and exits; mounted in compose as a separate service the
#               `app` waits on. Carries the full deps because prisma 7
#               loads prisma.config.ts via jiti + the file imports dotenv.
#   runner    — minimal runtime serving the Next.js standalone server.
#               Default build target.
#
# Prisma 7 uses the PrismaPg driver adapter rather than a native Rust
# engine, so alpine works at every stage — no glibc/musl bridge needed.

ARG NODE_VERSION=22-alpine

# ---------------------------------------------------------------------------
# deps — install once, reused by builder + migrator.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS deps
WORKDIR /app

# Copy lockfile + manifest first so this layer caches when deps don't change.
COPY package.json package-lock.json ./
# Prisma's postinstall runs `prisma generate`, which needs schema.prisma.
COPY prisma ./prisma

# `npm ci` installs both runtime + dev deps by default. The builder needs
# typescript/next-build; the migrator needs dotenv (loaded by the config
# file at module-load time). The runner doesn't carry this node_modules
# forward — it ships the trimmed copy emitted into .next/standalone.
RUN npm ci

# ---------------------------------------------------------------------------
# builder — generate the Prisma client + build the Next.js standalone server.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js doesn't require a public/ directory, but the runner stage copies
# it unconditionally. Ensure it exists so the COPY doesn't fail on repos
# (like this one) that don't ship static assets.
RUN mkdir -p public

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Next.js's page-data collection step evaluates every route module at build
# time, including the API routes that pull in lib/db.ts → createClient(),
# which validates DATABASE_URL eagerly. No query is actually made (every
# route is force-dynamic), but the module load needs SOMETHING here. The
# real URL is injected by compose at runtime; this value is never used to
# open a connection.
ENV DATABASE_URL=postgresql://build:build@localhost:5432/build

# The Prisma client was already generated by `prisma generate` in the deps
# stage's npm postinstall hook (which ran before prisma.config.ts was on
# disk — so it used schema.prisma alone and didn't need DATABASE_URL).
# COPY --from=deps brought the generated client over in node_modules; the
# trace pass in `next build` pulls it into .next/standalone automatically.
# Re-running `prisma generate` here would fail because prisma.config.ts
# now exists and resolves env("DATABASE_URL") at load time.
RUN npm run build

# ---------------------------------------------------------------------------
# migrator — one-shot image that applies pending migrations and exits.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS migrator
WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY prisma ./prisma
COPY prisma.config.ts ./
COPY package.json ./

# `migrate deploy` is the production-safe migration verb: applies pending
# migrations, never resets, never prompts. Reads DATABASE_URL from env via
# prisma.config.ts.
CMD ["npx", "prisma", "migrate", "deploy"]

# ---------------------------------------------------------------------------
# runner — minimal runtime for the Next.js standalone server. DEFAULT target.
# ---------------------------------------------------------------------------
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Non-root user — the standalone server doesn't need privileges.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 nextjs

# .next/standalone is a self-contained mini-app: server.js + the traced
# subset of node_modules. .next/static and public are NOT traced — they
# have to be copied separately into the expected paths.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs
EXPOSE 3000

CMD ["node", "server.js"]
